export const FIELD_LABELS: Record<string, string> = {
  'first-name': 'first name',
  'last-name': 'last name',
  'identified-name': 'identified name',
  'preferred-name': 'preferred name',
  email: 'email address',
  phone: 'phone number',
  'contact-phone': 'contact phone',
  'contact-name': 'contact name',
  subject: 'subject',
  message: 'message',
  'referral-type': 'referral type',
  address: 'address',
  city: 'city',
  suburb: 'suburb',
  'area-code': 'area code',
  'referral-source': 'how you heard about us',
  services: 'services',
  'training-hours': 'training hours',
  'start-date': 'start date',
  'end-date': 'end date',
  'other-topic-details': 'other details',
};
