export const FIELD_LABELS: Record<string, string> = {
  'first-name': 'your first name',
  'last-name': 'your last name',
  'identified-name': 'identified name',
  email: 'your email address',
  phone: 'your phone number',
  'contact-phone': 'a contact phone number',
  'contact-name': 'a contact name',
  subject: 'a subject',
  message: 'a message',
  'referral-type': 'a referral type',
  address: 'an address',
  city: 'a city',
  suburb: 'a suburb',
  'area-code': 'an area code',
  'referral-source': 'who is making this referral',
  services: 'at least one service',
  'training-hours': 'training duration',
  'start-date': 'a start date',
  'end-date': 'an end date',
  'other-topic-details': 'other details',
};
